name: Run Azure Login Dev
on:
  workflow_dispatch:
  push:
    branches: [dev]

permissions:
  id-token: write
  contents: read
jobs:
  demo:
    runs-on: ubuntu-latest
    environment: Azure
    steps:
      - name: "Azure PowerShell login"
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CLIENT_ID }}
          tenant-id: ${{ secrets.TENANT_ID }}
          subscription-id: ${{ secrets.SUBSCRIPTION_ID }}
          enable-AzPSSession: true

      - name: "Install Az modules"
        run: |
           Install-Module -Name Az.Resources
        shell: pwsh
 
      - name: "Get resource groups"
        run: |
            Get-AzResourceGroup
        shell: pwsh
